### ISSUE TITLE
Dynamic feature compatibility

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [pablisco/auto-module#5]
Currently the modules are generated using DependencyHandlerScope as context, so they can't be referenced in the dynamic features mutable set

```
android { // this = BaseAppModuleExtension
    dynamicFeatures = mutableSetOf<String>(
        modules.features.users.name // I think name should work if we can access to this dependencies
    )
}
```

**Comment by pablisco** [comment]
@JavierSegoviaCordoba Is this working on the latest version? 
Should be able to do:
```
android {
    dynamicFeatures = setOf(autoModules.features.users.path)
}
```

**Comment by JavierSegoviaCordoba** [comment]
I will check it, meanwhile I close this issue
